#        _____             _      _____
#      / ____|           | |    / ____|
#     | (___   ___  _   _| |___| (___   __ ___   _____
#     \___ \ / _ \| | | | / __|\___ \ / _` \ \ / / _ \
#    ____) | (_) | |_| | \__ \____) | (_| |\ V /  __/
#   |_____/ \___/ \__,_|_|___/_____/ \__,_| \_/ \___|
#
# Made by Gerolmed for the EndRealm Network


max_draft_perms_steps:
  - 5
  - 10
  - 20
