name: BuildRealm
version: @version@
main: net.endrealm.buildrealm.BuildRealm
api-version: "1.15"
depend: [SlimeWorldManager, WorldEdit]

commands:
  draft:
    description: Base command for drafts
    usage: /draft create/list/leave
  group:
    description: Base command for Groups
    usage: /group create/list/open
