name: LostSoulsSave
version: @version@
main: net.endrealm.lostsouls.LostSoulsSave
api-version: 1.15
depend: [SlimeWorldManager]

commands:
  draft:
    description: Base command for drafts
    usage: /draft create/list/leave
